DATASET_NAME: "brats"
NUM_CLASSES: 4
IMAGE_SIZE: [240, 240]
USE_HU_WINDOW: false

LEARNING_RATE: 5.0e-4
NORMALIZATION_MODE: "global"

GLOBAL_STATS:
  t2f: {mean: 941.0089, std: 351.0287, min: 0.0, max: 4050.0}
  t1c: {mean: 2099.6694, std: 760.0310, min: 0.0, max: 20289.6}
  t1n: {mean: 803.4387, std: 174.5820, min: 0.0, max: 4191.0}
  t2w: {mean: 673.8523, std: 322.7553, min: 0.0, max: 3841.8}

CLIP_RANGE: [-3.0, 3.0]
TARGET_RANGE: [0.0, 1.0]

MEAN: [0.0]
STD: [1.0]

CUSTOM_CLASS_WEIGHTS: [0.3, 50.0, 7.0, 40.0]

FP_PENALTY_WEIGHT: 0.0
SKIP_EMPTY_SLICES: false
EARLY_STOPPING_PATIENCE: 50

DICE_WEIGHT: 0.5
FOCAL_WEIGHT: 0.5
